version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Joleia#1273
      POSTGRES_DB: carbon_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  dashboard:
      build: .
      command: streamlit run app/dashboard.py --server.port=8501 --server.address=0.0.0.0
      ports:
        - "8501:8501"
      environment:
        - PYTHONPATH=/code  # <--- This tells Python to look in the root folder
      env_file:
        - .env
      depends_on:
        - web
        - db

volumes:
  postgres_data: